// eslint-disable-next-line quotes
export const GET_USER_CURRENT_LOCATION_LOADING =
  "GET_USER_CURRENT_LOCATION_LOADING";
export const GET_USER_CURRENT_LOCATION_SUCCESS =
  "GET_USER_CURRENT_LOCATION_SUCCESS";
export const GET_USER_CURRENT_LOCATION_ERROR =
  "GET_USER_CURRENT_LOCATION_ERROR";

export const GET_VEHICLE_DETAILS_LOADING = "GET_VEHICLE_DETAILS_LOADING";
export const GET_VEHICLE_DETAILS_SUCCESS = "GET_VEHICLE_DETAILS_SUCCESS";
export const GET_VEHICLE_DETAILS_ERROR = "GET_VEHICLE_DETAILS_ERROR";
